### ISSUE TITLE
Add `gethomepage/homepage` to hosted section

### ISSUE THREAD

**Issue by aureq** [jnmcfly/awesome-startpage#31]
Please add [`gethomepage/homepage`](https://github.com/gethomepage/homepage) to the hosted section.

Thank you.

**Comment by jnmcfly** [comment]
Hi @aureq  ,

Thank you for your contribution/suggestion! To streamline our workflow and ensure all changes are properly tracked and reviewed, we prefer that updates be submitted through a pull request.

If you're unfamiliar with how to create a pull request, GitHub has a comprehensive guide available [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). This resource should provide all the information you need.

Thanks for understanding and for your contribution!
