### ISSUE TITLE
N3WT48 - A new tab page in cyberpunk style

### ISSUE THREAD

**Issue by robbieh** [jnmcfly/awesome-startpage#32]
https://github.com/robbieh/N3WT48
Works as static files or hosted.

**Comment by jnmcfly** [comment]
Hi @robbieh ,

Thank you for your contribution/suggestion! To streamline our workflow and ensure all changes are properly tracked and reviewed, we prefer that updates be submitted through a pull request.

If you're unfamiliar with how to create a pull request, GitHub has a comprehensive guide available [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). This resource should provide all the information you need.

Thanks for understanding and for your contribution!
